spring:
  kafka:
    properties:
      schema.registry.url: http://localhost:8081
      auto.register.schemas: false

    bootstrap-servers: localhost:19092, localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer